* 使用左 Shift 切换 emacs-rime 的状态

這兩天折騰了 WSL 下的 Emacs，使用體驗比 Windows 原生要好了不少，但是有一個問題
十分影響使用體驗——WSL 下無法使用中文輸入法。這個問題本來有兩種解決方案——在 WSL
下使用 fcitx，或者使用 Emacs 內置的 emacs-rime（不得不說，Emacsers 眞的牛，這都
集成進來了！）。然而，前一種方法的參考資料很少，僅有資料寫到的方法（例如[[https://patrickwu.space/2019/10/28/wsl-fcitx-setup-cn/][這一篇]]）
我也試了，並不管用，查了很多資料也無法解決，我暫時認定是 DBus 相關的問題使輸入
法無法工作。後一種方法，即使用內置的 emacs-rime，確實非常爽，也十分可靠，不需要
依賴任何操作系統和外部程序，但就是有一點我十分難以接受—— emacs-rime 無法使用左
shift 鍵在中文和西文狀態之間切換。

emacs-rime 的開發者在 issues 中給很多人解釋過，Emacs 無法接收單獨一個 modifier
key 作爲輸入，因此無法使用單獨的左 Shift 鍵來切換中西文狀態。然而，我並不是袛需
要使用 Emacs 一個軟件，如果 Emacs 和其它軟件在輸入中文這麼簡單的一件事情上都有
着不同的按鍵的話，是一件非常別扭的事情。我想，我一定要解決它。

最後，經過大量調查，最終方法還是 AutoHotkey 腳本。腳本的核心內容如下：

#+begin_src autohotkey
  SetTitleMatchMode, 1
  #IfWinActive emacs
  Shift & AppsKey::Return
  Shift::Send ^\
#+end_src

大概意思是：
- 第一行和第二行，使腳本的功能衹對名稱以「emacs」開頭的窗口生效。
- 第三行，使得所有 Shift 組合鍵的功能不受影響。
- 第四行，使得單獨被按下的 Shift 發送 Ctrl+\ 序列，即 Emacs 中的切換輸入法函數。

這個腳本也在我的 dot-files 倉庫下。

衹要把這個腳本加入開機啟動，Emacs 的使用體驗就無比高了。從此開始，不管在什麼操
作系統、什么運行環境（甚至是純服務器環境）下，都態穩定地使用 rime 輸入法了！
