* 在 Windows 下使用 =opencc.el=

在 Windows 下正常使用 =opencc.el= 有点儿麻烦，以下是我的折腾过程。

既然您在看这篇文章，我默认您对 =opencc.el= 有一些基本的瞭解：[[https://github.com/BYVoid/OpenCC][OpenCC]] 是一個開源的
中文簡繁轉換項目，提供了一個命令行軟件，以及 JavaScript、Python、C/C++ 等語言的
binding；而 =opencc.el= 是一個使用 OpenCC 來在 Emacs 內部進行中文轉換的 Elisp 包。
如果您沒有這種程度的瞭解，建議您先使用搜索引擎調研一下。

** Windows 平臺特有的問題

我第一次使用 OpenCC 是在 Linux 平臺下，具體地說，是 Arch Linux。那時安裝 OpenCC，
一句 =pacman -S opencc= 就搞定了，開箱即用。在其它 Linux 發行版或 Mac 系統上應該
也是差不多的，我的配置應該衹要像這樣安裝了 OpenCC 就能用了。

在這些平臺上能開箱即用的原因，是因爲包管理器完成了下載、安裝、路徑等一系列過程。
但是在大名鼎鼎的 Microsoft Windows 10 上，就沒這麼容易了。我首先在 =scoop= 上搜
索有沒有 OpenCC。如果你不知道什么是 =scoop=，也不需要去瞭解了，因爲 =scoop= 上沒
有 OpenCC。Chocolatey 我也試過了，也沒有。

“包管理器”上沒有，那我手動安裝總行吧？遺憾的是，一開始，我還沒分清 OpenCC 的命令
行程序和庫文件。我安裝了 =opencc= 這個 Python 包，但是發現它衹是個庫，並沒有可執
行程序，也不能被 =opencc.el= 使用。我又安裝了另一個名爲
=opencc-python-reimplemented= 的包，它包含了一個可執行程序，和原版 OpenCC 的接口
是一致的，但是這個包是第三方創建的，並且不是很新，我還是對它持懷疑態度。

OpenCC 的 GitHub 頁面上是提供了 Windows 的預編譯包的，但是前幾天那個鏈接我點進去
都報錯。過幾天後，點進去能下載了，我就打算試一下這種版本。設置好了 PATH 後，可以
從 PowerShell 命令行中運行 OpenCC 了，我很高興，以爲問題就此解決了。

但是很快新問題就出現了，雖然 =opencc= 這個命令現在可以在命令行中運行了，但是它的
配置文件並不能在命令行中被找到，必須使用 =-c= 参數提供完整配置路徑才能正常運行。

** 解決問題的過程

我嘗試的第一個方案，是使用之前試過的 =opencc-python-reimplemented= 包代替，因爲
它能正常找到配置文件。但是它必須由 =python -m opencc= 來運行。於是我在 Emacs 中，
將 =opencc-command= 變量設置爲了 =python -m opencc=，不料 Elisp 不支持以這樣的命
令創建進程，提示 =python -m opencc= 這個文件找不到。

於是我就想辦法單獨運行 =opencc.py= 文件。我確保 PATHEXT 環境變量中有 =.py= 後綴，
然後把 =opencc-command= 設置成了 =opencc.py= 文件的路徑。不料 Emacs 還是無法執行
這樣的命令，報錯原因我給忘掉了。看來衹能用 =.exe= 文件了。

回到 Windows 預編譯的 =opencc.exe=。不就是找不到配置文件嗎，我指定配置文件的完整
路徑就行了。於是我在我的 =custom.el= 中加入了如下語句：

#+begin_src emacs-lisp
  ;; OpenCC configuration for Windows.
  (setq opencc-configuration-files-prefix
	"C:/Zybox/projects/windows-portable-tools/opencc/share/opencc/"
	opencc-configuration-files-suffix
	".json"
	opencc-configuration-files-original
	'("s2t" "t2s" "s2tw" "tw2s" "s2hk" "hk2s" "s2twp" "tw2sp")
	opencc-configuration-files nil)
  (dolist (filename opencc-configuration-files-original)
    (let ((fullpath
	   (concat opencc-configuration-files-prefix
		   filename
		   opencc-configuration-files-suffix)))
      (add-to-list 'opencc-configuration-files fullpath t)))
#+end_src

註意，這段代碼衹有 Windows 需要用，並且不是各機器通用的，配置文件的具體位置得跟
據實際情況來設置，所以我把它放在 =custom.el= 中，而沒有放在主配置裏。這樣一來，
=opencc.el= 的配置選擇界面也會顯示配置的完整路徑，看起來有一點點亂，但總歸是能用
了。
