;;; zy-defaults.el --- Saner defaults. -*- lexical-binding: t -*-

;;; Commentary:

;; This file provides the `+defaults' module of the configuration.

;; It sets up some saner default values, which are too basic or too generic to
;; be put into individual modules.
;;
;; Emacs is known to have impractical default settings, which prevents it from
;; "work out of the box". Most of them are due to historical reasons, since
;; Emacs is almost 50 years old. People argue that Emacs was not designed to
;; work out of the box, and is intended to be heavily tweaked. Well, that is
;; what we do here and in the whole configuration.

;;; Code:

(require 'zylib)

;; Do not create auto save or backup files. It is not 1976 now, and every text
;; editor don't create auto save files. Besides, we have Git.
(setq auto-save-default nil
      make-backup-files nil)

;; By default, Emacs asks the user if it should kill processes on exit. VS Code
;; does not do that, and I find it annoying to type "yes" every type, so just
;; let Emacs kill processes automatically.
(setq confirm-kill-processes nil)

;; Also kill buffers which have a running process without confirmation.
(setq kill-buffer-query-functions (delq 'process-kill-buffer-query-function
                                        kill-buffer-query-functions))

;; When deleting a file, always use the system's trash can if possible.
(setq delete-by-moving-to-trash t)

;; Do not disable any command by default, since I am already a experienced Emacs
;; user.
(setq disabled-command-function nil)

;; Set up a informational frame title. Besides, my AutoHotkey scripts recognize
;; my Emacs window by the \"ZyEmacs\" prefix set here.
(setq frame-title-format '((if *wsl* "ZyEmacsWSL@" "ZyEmacs@")
                           (:eval (or
                                   (file-remote-p default-directory 'host)
                                   system-name))
                           " [%b]"))

;; I usually use a Hybrid font like Sarasa Gothic, which contains tremendous
;; amout of CJK glyphs. Disable compacting of font makes redisplay faster.
(setq inhibit-compacting-font-caches t)

;; Do not show the startup screen. If the `+dashboard' module is enabled, it
;; will provide a beautiful and feature-rich dashboard on startup instead.
(setq inhibit-startup-screen t)

;; Do not report warnings and errors produced by asynchronous native
;; compilation, since they do not matter in most occasions and there is little
;; we can do with warnings generated by third-party packages.
(when (featurep 'native-compile)
  (setq-default native-comp-async-report-warnings-errors nil))

;; Hide commands in M-x which do not apply to the current mode.
(setq read-extended-command-predicate #'command-completion-default-include-p)

;; The default value of `read-process-output-max' (4 kB) is too low considering
;; some language server responses are from 800 kB to 3 MB. So set it to 1 MB as
;; suggested by Lsp-mode.
(setq read-process-output-max (* 1024 1024))

;; Save existing clipboard text into kill ring before replacing it. This saves
;; me so many time!
(setq save-interprogram-paste-before-kill t)

;; Uniquify buffer names in a saner way. See the doc for details.
(setq uniquify-buffer-name-style 'forward)

;; Never use GUI dialog boxes since they cause problems on WSLg.
(setq use-dialog-box nil)

(provide 'zy-defaults)

;;; zy-defaults.el ends here
